# Generated by Django 4.2.8 on 2024-08-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=37, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
