# Generated by Django 4.2.8 on 2024-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_category_color_category_relations_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(db_index=True, editable=False, help_text='max_length= len(model_name) + 33', max_length=41, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(db_index=True, editable=False, help_text='max_length= len(model_name) + 33', max_length=37, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(db_index=True, editable=False, help_text='max_length= len(model_name) + 33', max_length=35, unique=True),
        ),
    ]
