# Generated by Django 4.2.8 on 2024-10-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='value',
            field=models.SmallIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
