# Generated by Django 4.2.8 on 2024-10-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_priority_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='value',
            new_name='order',
        ),
    ]
