# Generated by Django 4.2.8 on 2024-10-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_priority_group_alter_priority_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='group',
        ),
    ]
