# Generated by Django 4.2.8 on 2024-11-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_rename_latitude_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='long',
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Coordenada de longitud.', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, help_text='Coordenada de latitud.', max_digits=19, null=True),
        ),
    ]
