# Generated by Django 4.2.8 on 2024-11-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_remove_location_long_location_lng_alter_location_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección completa de la ubicación.', max_length=255),
        ),
    ]
