# Generated by Django 4.2.8 on 2024-07-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='priority',
            field=models.CharField(choices=[('highest', 'highest'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('lowest', 'lowest')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('highest', 'highest'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('lowest', 'lowest')], default='medium', max_length=50),
        ),
    ]
