# Generated by Django 4.2.8 on 2024-07-11 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_scheduledtask_priority_alter_task_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenancePlan',
            new_name='Plan',
        ),
        migrations.RenameField(
            model_name='scheduledtask',
            old_name='maintenance_plan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='maintenance_plan',
            new_name='plan',
        ),
    ]
