# Generated by Django 4.2.8 on 2024-08-05 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_task_code_alter_task_created_by_alter_task_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
