# Generated by Django 4.2.8 on 2024-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_task_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=37, unique=True),
        ),
    ]
