# Generated by Django 4.2.8 on 2024-08-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_alter_task_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('to_validate', 'to_validate'), ('completed', 'completed')], default='to_do', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('to_validate', 'to_validate'), ('completed', 'completed')], max_length=50),
        ),
    ]
