# Generated by Django 4.2.8 on 2024-08-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_issue_issuefile_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuefile',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_issue_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
