# Generated by Django 4.2.8 on 2024-08-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_issue_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='requesting_unit',
        ),
    ]
