# Generated by Django 4.2.8 on 2024-09-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('scheduled', 'scheduled'), ('rescheduled', 'rescheduled'), ('executed', 'executed'), ('to_validate', 'to_validate'), ('completed', 'completed')], default='to_do', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('scheduled', 'scheduled'), ('rescheduled', 'rescheduled'), ('executed', 'executed'), ('to_validate', 'to_validate'), ('completed', 'completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='management.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
