# Generated by Django 4.2.8 on 2024-10-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_plan_end_date_alter_plan_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issuefile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestingunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
