# Generated by Django 4.2.8 on 2024-10-09 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Formato hexadecimal (ej. #FF00AA)', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='El color debe ser un valor hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Formato hexadecimal (ej. #FF00AA)', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='El color debe ser un valor hexadecimal válido', regex='^#[0-9A-Fa-f]{6}$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
