# Generated by Django 4.2.8 on 2024-10-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_issue_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('recibido', 'recibido'), ('tarea_creada', 'tarea_creada'), ('rechazado', 'rechazado'), ('completado', 'completado')], default='recibido', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('por_hacer', 'por_hacer'), ('en_ejecucion', 'en_ejecucion'), ('bloqueado', 'bloqueado'), ('programado', 'programado'), ('reprogramado', 'reprogramado'), ('no_ejecutable', 'no_ejecutable'), ('completado', 'completado')], default='por_hacer', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('emergente', 'emergente'), ('preventiva', 'preventiva')], default='preventiva', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('por_hacer', 'por_hacer'), ('en_ejecucion', 'en_ejecucion'), ('bloqueado', 'bloqueado'), ('programado', 'programado'), ('reprogramado', 'reprogramado'), ('no_ejecutable', 'no_ejecutable'), ('completado', 'completado')], max_length=50),
        ),
    ]
