# Generated by Django 4.2.8 on 2024-10-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_issue_status_alter_task_status_alter_task_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueStatus',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
