# Generated by Django 4.2.8 on 2024-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_rename_content_taskcomment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='order',
        ),
    ]
