# Generated by Django 4.2.8 on 2024-11-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_location'),
        ('management', '0025_remove_issuecomment_order_remove_taskcomment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIssueLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='management.issue')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.location')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='management.task')),
            ],
            options={
                'unique_together': {('task', 'issue')},
            },
        ),
    ]
