# Generated by Django 4.2.8 on 2024-11-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_rename_latitude_location_lat_and_more'),
        ('management', '0026_taskissuelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.location'),
        ),
        migrations.DeleteModel(
            name='TaskIssueLocation',
        ),
    ]
