# Generated by Django 4.2.8 on 2024-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('dni', 'dni'), ('passport', 'passport')], max_length=10),
        ),
    ]
