# Generated by Django 4.2.8 on 2024-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_custompermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
